version: "3.2"
services:
  backend_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: on-failure
    user: root
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "pass@word1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - ./external_resource/docker/sqlserver:/var/opt/mssql